### ISSUE TITLE
Application crashes on 4.4.2

### ISSUE THREAD

**Issue by doerfli** [doerfli/leavemealone#33]
01-13 15:53:21.723 2096-2096/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: li.doerf.leavemealone, PID: 2096
                                                 java.lang.ClassCastException: android.graphics.drawable.ColorDrawable cannot be cast to android.support.v7.widget.RoundRectDrawableWithShadow
                                                     at android.support.v7.widget.CardViewEclairMr1.getShadowBackground(CardViewEclairMr1.java:159)
                                                     at android.support.v7.widget.CardViewEclairMr1.getMinWidth(CardViewEclairMr1.java:150)
                                                     at android.support.v7.widget.CardView.onMeasure(CardView.java:181)
                                                     at android.view.View.measure(View.java:16497)
                                                     at android.support.v7.widget.RecyclerView$LayoutManager.measureChildWithMargins(RecyclerView.java:6874)
                                                     at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1396)
                                                     at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1333)
                                                     at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:562)
                                                     at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2900)
                                                     at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3071)
                                                     at android.view.View.layout(View.java:14817)
                                                     at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
                                                     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
                                                     at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
                                                     at android.view.View.layout(View.java:14817)
                                                     at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                     at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                     at android.view.View.layout(View.java:14817)
                                                     at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                     at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1037)
                                                     at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:747)
                                                     at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
                                                     at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1156)
                                                     at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:760)
                                                     at android.view.View.layout(View.java:14817)
                                                     at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                     at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1043)
                                                     at android.view.View.layout(View.java:14817)
                                                     at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                     at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                     at android.view.View.layout(View.java:14817)
                                                     at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
                                                     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
                                                     at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
                                                     at android.view.View.layout(View.java:14817)
                                                     at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                     at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                     at android.view.View.layout(View.java:14817)
                                                     at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
                                                     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
                                                     at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
                                                     at android.view.View.layout(View.java:14817)
                                                     at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                     at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                     at android.view.View.layout(View.java:14817)
                                                     at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                     at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1983)
                                                     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1740)
                                                     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:996)
                                                     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5600)
                                                    at android.view.Choreographer$C

**Comment by doerfli** [comment]
According to https://code.google.com/p/android/issues/detail?id=77843 the solution is wrapping the CardView in a FrameLayout
